routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});


Route::get('/test', function () {
    return view('admin.page.blank');
});


Route::resource('dashboard/news', 'News\ManageNews');
Route::resource('dashboard/category', 'Category\ManageCategory');
Route::resource('dashboard/tag', 'Tag\ManageTag');


Route::get('datatables/category', 'Category\ManageCategory@datatables')->name('datatables.cat');
Route::get('datatables/tag', 'Tag\ManageTag@datatables')->name('datatables.tag');
Route::get('datatables/news', 'News\ManageNews@datatables')->name('datatables.news');
Route::get('delete/delete/{id}', 'News\ManageNews@destroy')->name('delete.news');
Route::get('post/activate/{id}', 'News\ManageNews@activate')->name('activate.news');
Route::get('post/deactivate/{id}', 'News\ManageNews@deactivate')->name('deactivate.news');
Route::get('post/facebookpage/{id}', 'News\ManageNews@PostFacebook')->name('post.facebookpage');
Route::get('post/twitter/{id}', 'News\ManageNews@Posttwitter')->name('post.twitter');


///slider
///
///
///
Route::get('slider/create', 'frontend\ManageSlider@Create')->name('slider.create');
Route::post('slider/create', 'frontend\ManageSlider@Store')->name('slider.store');
Route::get('slider', 'frontend\ManageSlider@Index')->name('slider.index');
Route::get('slider/delete/{id}', 'frontend\ManageSlider@delete')->name('slider.delete');
Route::get('slider/datatable', 'frontend\ManageSlider@datatables')->name('slider.datatable');


//feedback


Route::get('feedback/create', 'Feedback\ManageFeedback@Create')->name('feedback.create');
Route::post('feedback/create', 'Feedback\ManageFeedback@Store')->name('feedback.store');
Route::get('feedback', 'Feedback\ManageFeedback@Index')->name('feedback.index');
Route::get('feedback/delete/{id}', 'Feedback\ManageFeedback@delete')->name('feedback.delete');
Route::get('feedback/details/{id}', 'Feedback\ManageFeedback@details')->name('feedback.details');
Route::get('feedback/datatable', 'Feedback\ManageFeedback@datatables')->name('feedback.datatable');


////ads
///
///

Route::get('ads/manageads', 'Ad\Manageads@viewPage')->name('ads.manage');




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Category/ManageCategory.php
<?php

namespace App\Http\Controllers\Category;

use App\Model\Category\PrimaryCategory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Yajra\Datatables\Datatables;

class ManageCategory extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.page.category.all');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.page.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $a = new PrimaryCategory();
        $a->description = $request->description;
        $a->slug = $request->slug;
        $a->name = $request->name;
        $a->save();
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $a = PrimaryCategory::findorfail($id);
        return view('admin.page.category.edit')->with(['cat' => $a]);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $a = PrimaryCategory::findorfail($id);
        return view('admin.page.category.edit')->with(['cat' => $a]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $a = PrimaryCategory::findorfail($id);
        $a->description = $request->description;
        $a->slug = $request->slug;
        $a->name = $request->name;
        $a->save();
        return  redirect( route('category.create'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function datatables()
    {

        $invoices = PrimaryCategory::select(
            [
                'id',
                'name',
                'created_at',
            ]);

        return Datatables::of($invoices)



            /*'.route('category.edit',$invoice->id).'*/



         ->addColumn('action', function ($invoice) {
                return '<a href="'.route('category.edit',$invoice->id).'" class=" btn btn-xs btn-primary" title="View details"><i class="la la-edit"></i>View Details</a>';
            })


          ->rawColumns(['action'])
         ->orderColumn('id', 'created_at $1')
            ->make();
    }

}

resources/views/admin/page/category/all.blade.php
@extends('admin.base')

@section('content')

    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h3 class="text-themecolor">Animation</h3>
            </div>
            <div class="col-md-7 align-self-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                    <li class="breadcrumb-item">pages</li>
                    <li class="breadcrumb-item active">Animation</li>
                </ol>
            </div>
            <div>
                <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            This is some text within a card block.
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End PAge Content -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Right sidebar -->
            <!-- ============================================================== -->
            <!-- .right-sidebar -->

            <!-- ============================================================== -->
            <!-- End Right sidebar -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->

    @endsection

resources/views/admin/page/category/create.blade.php
@extends('admin.base')

@section('content')

    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h3 class="text-themecolor">Create News</h3>
            </div>
            <div class="col-md-7 align-self-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                    <li class="breadcrumb-item">pages</li>
                    <li class="breadcrumb-item active">Animation</li>
                </ol>
            </div>
            <div>
                <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <!-- Row -->
            <div class="row">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Create New Category</h4>
                            <h6 class="card-subtitle">Donot Re create Same Category</h6>
                            <form class="form p-t-20"

                                  role="form" method="post"
                                  action="{{ route('category.store') }}"
                            >
                                {{ csrf_field() }}
                                <div class="form-group">
                                    <label for="exampleInputuname">Category Name</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="ti-marker-alt"></i></div>
                                        <input type="text" class="form-control" name="name" placeholder="Category Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Category Slug</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="ti-vector"></i></div>
                                        <input type="text" class="form-control" name="slug" placeholder="Category Slug">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="pwd1">Category Description</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="ti-more-alt"></i></div>
                                        <input type="text" class="form-control" name="description" placeholder="Category Description ">
                                    </div>
                                </div>


                                <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Submit</button>
                                <button type="reset" class="btn btn-inverse waves-effect waves-light">Cancel</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Category List</h4>




                            <div class="table-responsive m-t-40">



                                <table id="product-table" class="display nowrap table table-hover table-striped table-bordered"
                                cellspacing="0" width="100%">
                                    <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Date</th>
                                        <th>Details</th>

                                    </tr>
                                    </thead>
                                    <tfoot>
                                    <tr>
                                        <th>Name</th>
                                        <th>Date</th>
                                        <th>Details</th>

                                    </tr>
                                    </tfoot>

                                </table>


                              {{--  <table class="table table-striped table-bordered" id="product-table">
                                    <thead class="thead-dark">
                                    <tr>
                                        <th>Invoice ID</th>
                                        <th >Date</th>

                                        <th>DETAILS</th>



                                    </tr>
                                    </thead>
                                </table>--}}






                            </div>














                            </div>
                    </div>
                </div>

            </div>
            <!-- Row -->

            <!-- ============================================================== -->
            <!-- End PAge Content -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Right sidebar -->
            <!-- ============================================================== -->
            <!-- .right-sidebar -->

            <!-- ============================================================== -->
            <!-- End Right sidebar -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->

    @endsection

@section('footer_script')

    <!-- start - This is for export functionality only -->
        <script src="{{asset('js/jquery.dataTables.min.js')}}"></script>
        <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
        <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
        <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
        <!-- end - This is for export functionality only -->




        <script>
            $(function() {
                $('#product-table').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: '{{route('datatables.cat')}}',
                    order: [ [0, 'desc'] ],
                    columns: [
                        { data: 'name', name: 'name' },
                        { data: 'created_at', name: 'created_at' },
                        {data: 'action', name: 'action', orderable: false, searchable: false},

                    ]
                });

            });
        </script>




@endsection

resources/views/admin/page/category/edit.blade.php
@extends('admin.base')

@section('content')

    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h3 class="text-themecolor">Animation</h3>
            </div>
            <div class="col-md-7 align-self-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                    <li class="breadcrumb-item">pages</li>
                    <li class="breadcrumb-item active">Animation</li>
                </ol>
            </div>
            <div>
                <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Create New Category</h4>
                            <h6 class="card-subtitle">Donot Re create Same Category</h6>
                            <form class="form p-t-20"

                                  role="form" method="post"
                                  action="{{ route('category.update',$cat->id) }}"
                            >
                                <input name="_method" type="hidden" value="PUT">
                                {{ csrf_field() }}
                                <div class="form-group">
                                    <label for="exampleInputuname">Category Name</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="ti-marker-alt"></i></div>
                                        <input type="text" class="form-control" value="{{$cat->name}}" name="name" placeholder="Category Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Category Slug</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="ti-vector"></i></div>
                                        <input type="text" class="form-control" value="{{$cat->slug}}" name="slug" placeholder="Category Slug">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="pwd1">Category Description</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="ti-more-alt"></i></div>
                                        <input type="text" class="form-control" value="{{$cat->description}}" name="description" placeholder="Category Description ">
                                    </div>
                                </div>


                                <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Submit</button>
                                <button type="reset" class="btn btn-inverse waves-effect waves-light">Cancel</button>
                            </form>
                        </div>
                    </div>
                </div>


            </div>
            <!-- ============================================================== -->
            <!-- End PAge Content -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Right sidebar -->
            <!-- ============================================================== -->
            <!-- .right-sidebar -->

            <!-- ============================================================== -->
            <!-- End Right sidebar -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->

    @endsection