routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});


Route::get('/test', function () {
    return view('admin.page.blank');
});


Route::resource('dashboard/news', 'News\ManageNews');
Route::resource('dashboard/category', 'Category\ManageCategory');
Route::resource('dashboard/tag', 'Tag\ManageTag');


Route::get('datatables/category', 'Category\ManageCategory@datatables')->name('datatables.cat');
Route::get('datatables/tag', 'Tag\ManageTag@datatables')->name('datatables.tag');
Route::get('datatables/news', 'News\ManageNews@datatables')->name('datatables.news');
Route::get('delete/delete/{id}', 'News\ManageNews@destroy')->name('delete.news');
Route::get('post/activate/{id}', 'News\ManageNews@activate')->name('activate.news');
Route::get('post/deactivate/{id}', 'News\ManageNews@deactivate')->name('deactivate.news');
Route::get('post/facebookpage/{id}', 'News\ManageNews@PostFacebook')->name('post.facebookpage');
Route::get('post/twitter/{id}', 'News\ManageNews@Posttwitter')->name('post.twitter');


///slider
///
///
///
Route::get('slider/create', 'frontend\ManageSlider@Create')->name('slider.create');
Route::post('slider/create', 'frontend\ManageSlider@Store')->name('slider.store');
Route::get('slider', 'frontend\ManageSlider@Index')->name('slider.index');
Route::get('slider/delete/{id}', 'frontend\ManageSlider@delete')->name('slider.delete');
Route::get('slider/datatable', 'frontend\ManageSlider@datatables')->name('slider.datatable');


//feedback


Route::get('feedback/create', 'Feedback\ManageFeedback@Create')->name('feedback.create');
Route::post('feedback/create', 'Feedback\ManageFeedback@Store')->name('feedback.store');
Route::get('feedback', 'Feedback\ManageFeedback@Index')->name('feedback.index');
Route::get('feedback/delete/{id}', 'Feedback\ManageFeedback@delete')->name('feedback.delete');
Route::get('feedback/details/{id}', 'Feedback\ManageFeedback@details')->name('feedback.details');
Route::get('feedback/datatable', 'Feedback\ManageFeedback@datatables')->name('feedback.datatable');


////ads
///
///

Route::get('ads/manageads', 'Ad\Manageads@viewPage')->name('ads.manage');




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/News/ManageNews.php
<?php

namespace App\Http\Controllers\News;

use App\Model\Category\PrimaryCategory;
use App\Model\Post\Post;
use App\Model\Post\PostToPrimaryImagebg;
use App\Model\Post\PostToPrimaryImageSmall;
use App\Model\Post\PrimaryCategoryToPost;
use App\Model\Post\TagToPost;
use App\Model\Tags\Tag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Image;
use Jelovac\Bitly4laravel\Bitly4laravel;
use Toolkito\Larasap\SendTo;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\File;
use Input;
use Bitly;
class ManageNews extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {




        return view('admin.page.news.all');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $c = PrimaryCategory::all();
        $t = Tag::all();
       return view('admin.page.news.create')->with([
           'cs' => $c,
           'ts' => $t,
       ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $a = new Post();
        $a->title = $request->title;
        $a->slug = $request->slug;
        $a->description = $request->description;
        $a->primary_category_to_post_id = $request->primary_category_to_post_id;
        $a->save();




        $lastsaved = $a->id;

        $tagsreq =  $request->input('tags');


        $findcat = PrimaryCategory::findorfail($request->primary_category_to_post_id)->first();


        $postcat = new PrimaryCategoryToPost();
        $postcat->name = $findcat->name;
        $postcat->slug = $findcat->slug;
        $postcat->description = $findcat->description;
        $postcat->post_id = $lastsaved;
        $postcat->save();




        $tags =  explode(",", $tagsreq);

      foreach($tags as $tag){
            $tag2 = new TagToPost();
            $tag2->post_id = $a->id;
            $tag2->name = $tag;
            $tag2->slug = $tag;
            $tag2->description = $tag;
            $tag2->save();
        }








      //  return response()->json($tags);













        $path2 = $request->file('bgimage')->store('news/bgimage/images','public');


      $date = time();


        $img =    Image::make($request->file('smallimage'))->resize(300, null, function ($constraint) {
        $constraint->aspectRatio();
    })->save('newsimages/'.$date.'.jpg','public');








       $ab = new PostToPrimaryImagebg();

        $ab->name = $request->title;
        $ab->post_id = $lastsaved;

        $ab->location = $path2;

        $ab->path = 'news/bgimage/images/';

        $ab->save();


        $ac = new PostToPrimaryImageSmall();

        $ac->name = $request->title;
        $ac->post_id = $lastsaved;

        $ac->location = 'newsimages/'.$date.'.jpg';

        $ac->path = 'newsimages/';

        $ac->save();




        $return_id = $a->id;


        return redirect(route('news.edit',$return_id));









        }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $a = Post::findorfail($id);

        return view('admin.page.news.view')->with(['n' => $a]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $a = Post::findorfail($id);

        return view('admin.page.news.edit')->with(['n' => $a]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $a =  Post::findorfail($id);
        $a->title = $request->title;

        $a->description = $request->description;
        $a->save();















        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $d = Post::findorfail($id);
        $d->delete();
        return redirect(route('news.index'));
    }


        public function datatables()
    {

        $invoices = Post::select(
            [
                'id',
                'title',
                'slug',
                'created_at',
            ]);

        return DataTables::of($invoices)



            /*'.route('category.edit',$invoice->id).'*/



            ->addColumn('action', function ($invoice) {
                return '<a href="'.route('news.edit',$invoice->id).'" class=" btn btn-xs btn-primary" title="View details"><i class="la la-edit"></i>View Details</a>';
            })

            ->addColumn('delete', function ($invoice) {
                return '<a href="'.route('delete.news',$invoice->id).'" class=" btn btn-xs btn-danger" title="Delete"><i class="la la-edit"></i>Delete</a>';
            })

            ->addColumn('tags', function ($invoice) {

                $a = TagToPost::where('post_id', $invoice->id)
                    ->select([
                        'name',
                    ])
                    ->get();

                // return $a;


                return $invoice->tag_to_posts->map(function($tag_to_posts) {
                    return ('<span class="badge badge-primary">'.$tag_to_posts->name.'</span>');
                })->implode('<br>');






                //  foreach ($a as $p) {


                // return '<button type="button" class="btn m-btn--pill    btn-outline-success">' . $p->name .' '.$p->color.' '.$p->size .'</button>';

                //   }
                //    return $k;




            })


            ->rawColumns(['action','delete','tags'])
            ->orderColumn('id', 'created_at $1')
            ->make();
    }

    public function PrimaryImageUpload(Request $request){

        $path2 = $request->file('qqfile')->store('news/bgimage/images','public');

        return response()->json($path2);

    }

    public function activate($id){
        $a = Post::findorfail($id);

        $a->activate = '1';

        $a->save();

        return back();
    }

    public function deactivate($id){
        $a = Post::findorfail($id);

        $a->activate = '0';

        $a->save();

        return back();
    }

    public function PostFacebook($id)
    {

        $post = Post::findorfail($id);

        $pathimage = 'https://manage.newsontop.news/storage/';

        $image = $post->post_to_primary_imagebgs->location;


        $slug = $post->slug;

        $pathnewsdetails = 'https://newsontop.news/details/' . $slug;

        $bitlyurl = Bitly::shorten($pathnewsdetails);
        // $bitlyurl = Bitly::shorten('http://google.com/');


        //  dd($bitlyurl->data->url);

        $smallurl = $bitlyurl->data->url;

        SendTo::Facebook(
            'photo',
            [
                'photo' => public_path('storage/' . $image),
                'message' => $post->title . ' ' . $smallurl
            ]
        );


        /* SendTo::Facebook(
             'link',
             [
                 'link' => $smallurl,
                 'message' => $post->title . ' ' . $smallurl
             ]
         );*/

        // $parsejson = json_decode($bitlyurl->data, true);


        return redirect(route('news.edit', $post->id));
    }


    public function Posttwitter($id)
    {

        $post = Post::findorfail($id);

        $pathimage = 'https://manage.newsontop.news/storage/';


        $slug = $post->slug;

        $pathnewsdetails = 'https://newsontop.news/details/' . $slug;

        $bitlyurl = Bitly::shorten($pathnewsdetails);
        // $bitlyurl = Bitly::shorten('http://google.com/');


        //  dd($bitlyurl->data->url);

        $smallurl = $bitlyurl->data->url;

        $image = $post->post_to_primary_imagebgs->location;


        /*  SendTo::Twitter($post->title . ' ' . $smallurl);*/


        SendTo::Twitter(
            $post->title . ' ' . $smallurl,
            [
                public_path('storage/' . $image),
            ]
        );

        // $parsejson = json_decode($bitlyurl->data, true);


        return redirect(route('news.edit', $post->id));
    }

}

resources/views/admin/page/news/all.blade.php
@extends('admin.base')

@section('content')

    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h3 class="text-themecolor">Animation</h3>
            </div>
            <div class="col-md-7 align-self-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                    <li class="breadcrumb-item">pages</li>
                    <li class="breadcrumb-item active">Animation</li>
                </ol>
            </div>
            <div>
                <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">



                            <div class="table-responsive m-t-40">



                                <table id="product-table" class="display nowrap table table-hover table-striped table-bordered"
                                       cellspacing="0" width="100%">
                                    <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th style="width: 50%">Title</th>
                                        <th>Tags</th>

                                        <th>Action</th>
                                        <th>Delete</th>

                                    </tr>
                                    </thead>
                                    <tfoot>
                                    <tr>
                                        <<th>Id</th>
                                        <th>Title</th>
                                        <th >Tags</th>

                                        <th>Action</th>
                                        <th>Delete</th>

                                    </tr>
                                    </tfoot>

                                </table>


                                {{--  <table class="table table-striped table-bordered" id="product-table">
                                      <thead class="thead-dark">
                                      <tr>
                                          <th>Invoice ID</th>
                                          <th >Date</th>

                                          <th>DETAILS</th>



                                      </tr>
                                      </thead>
                                  </table>--}}






                            </div>








                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End PAge Content -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Right sidebar -->
            <!-- ============================================================== -->
            <!-- .right-sidebar -->

            <!-- ============================================================== -->
            <!-- End Right sidebar -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->

    @endsection

    @section('footer_script')

        <!-- start - This is for export functionality only -->
            <script src="{{asset('js/jquery.dataTables.min.js')}}"></script>
            <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
            <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
            <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
            <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
            <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
            <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
            <!-- end - This is for export functionality only -->




            <script>
                $(function() {
                    $('#product-table').DataTable({
                        processing: true,
                        serverSide: true,
                        ajax: '{{route('datatables.news')}}',
                        order: [ [0, 'desc'] ],
                        columns: [
                            { data: 'id', name: 'id' },
                            { data: 'title', name: 'title' },
                            { data: 'tags', name: 'tags' },

                            {data: 'action', name: 'action', orderable: false, searchable: false},
                            {data: 'delete', name: 'delete', orderable: false, searchable: false}

                        ]
                    });

                });
            </script>




@endsection

resources/views/admin/page/news/create.blade.php
@extends('admin.base')

@section('content')






    <link href="{{asset('assets/plugins/dropzone-master/dist/dropzone.css')}}" rel="stylesheet" type="text/css" />
    <!-- Custom CSS -->



    <style>
        .ck-editor__editable {
            min-height: 400px;
        }
    </style>
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h3 class="text-themecolor">Create News</h3>
            </div>
            <div class="col-md-7 align-self-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                    <li class="breadcrumb-item">News</li>
                    <li class="breadcrumb-item active">Create News</li>
                </ol>
            </div>
            <div>







            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->

            <form class="form p-t-20"

                  role="form" method="post"
                  action="{{ route('news.store') }}"
                  enctype="multipart/form-data"
            >


            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Create New News</h4>

                                {{ csrf_field() }}
                                <div class="form-group">
                                    <label for="exampleInputuname">News Title</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="ti-marker-alt"></i></div>
                                        <input type="text"  class="form-control title-news" name="title" placeholder="News Title">
                                    </div>
                                </div>


                                <div class="form-group">

                            <textarea class="ck-editor__editable" name="description" id="my-editor"></textarea>
                                </div>


                        </div>
                    </div>

                </div>
            </div>






                <div class="row">
                    <div class="col-lg-6 col-md-12">
                        <div class="card">
                            <div class="card-body">



                                <div class="form-group">
                                    <label>Category</label>
                                    <select name="primary_category_to_post_id" class="form-control custom-select">
                                        <option>--Category--</option>


                                        @foreach($cs as $c)


                                        <option value="{{$c->id}}">{{$c->name}}</option>

                                            @endforeach
                                    </select>
                                </div>



                                {{--<div class="form-group">
                                    <label>Saved Tags</label>
                                <select class="select2 m-b-10 select2-multiple" style="width: 100%"
                                        multiple="multiple" data-placeholder="Choose">
                                    @foreach($ts as $t)
                                        <option value="AK">{{$t->name}}</option>

                                    @endforeach

                                </select>

                                </div>--}}
                                <div class="form-group">
                                    <label for="exampleInputuname">Slug</label>
                                    <div class="input-group">
                                        <div class="input-group-addon"><i class="ti-marker-alt"></i></div>
                                        <input type="text"  class="form-control category-slug"
                                               readonly name="slug" placeholder="Slug">
                                    </div>
                                </div>






                            </div>
                        </div>

                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Add news Tags</h4>



                                <div class="tags-default">
                                    <input type="text" value="" name="tags" data-role="tagsinput"
                                           placeholder="add tags" />



                                </div>


                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-12">


                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Add BG Image</h4>



                                <div class="tags-default">
                                    <input type="file"
                                           class="form-control"
                                           required
                                           name="bgimage"
                                           value=""


                                    >



                                </div>


                            </div>
                        </div>


                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Add Small Image</h4>



                                <div class="tags-default">
                                    <input type="file"
                                           class="form-control"
                                           required
                                           name="smallimage"
                                           value=""


                                    >



                                </div>


                            </div>
                        </div>
                    </div>



                    <div class="col-lg-6 col-md-12">

                    </div>













                </div>









<button type="submit">Submit</button>








            </form>
            <!-- ============================================================== -->
            <!-- End PAge Content -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Right sidebar -->
            <!-- ============================================================== -->
            <!-- .right-sidebar -->

            <!-- ============================================================== -->
            <!-- End Right sidebar -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->

    @endsection

    @section('footer_script')

        <!-- start - This is for export functionality only -->


            <script src="{{asset('js/switchery.min.js')}}"></script>
            <script src="{{asset('js/select2.full.min.js')}}"></script>

            <script src="{{asset('js/bootstrap-select.min.js')}}"></script>
            <script src="{{asset('js/bootstrap-tagsinput.min.js')}}"></script>
            <script src="{{asset('js/jquery.bootstrap-touchspin.min.js')}}"></script>
            <script src="{{asset('js/jquery.multi-select.js')}}"></script>



            <script src="//cdn.ckeditor.com/4.6.2/full/ckeditor.js"></script>
            <script>
                var options = {
                    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
                    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
                    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
                    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
                };
            </script>




            <script>
                CKEDITOR.replace('my-editor', options);
            </script>



            <script>
                $(document).ready(function() {
                    $('.js-example-basic-multiple').select2();
                });
            </script>

            <script>
                $(document).ready(function(){
                    $(".title-news").keyup(function(){

                        var cat_name_val = $( this ).val();
                        var actualSlug = cat_name_val.replace(/ /g,'-').toLowerCase()

                        $(".category-slug").val(actualSlug);



                    });
                });
            </script>





@endsection